### ISSUE TITLE
is MarkerSet always required?

### ISSUE THREAD

**Issue by marnunez** [aclouthier/auto-marker-label#1]
Hi! Is a MarkerSet.xml file required even if I have already labeld c3d files for training?

**Comment by aclouthier** [comment]
Hello! The algorithm uses a neural network to do the initial label prediction and then does some automatic corrections. The corrections rely on the marker set .xml definition, but you could, in theory, use just the neural network step without defining a marker set. 
The way the code is currently formulated though, it does need the marker set file. 
I'll consider updating it so that it could work without the marker set as well.

**Comment by marnunez** [comment]
Thanks! I ended up making my own OpenSIM custom MarkerSet.xml
