### ISSUE TITLE
ValueError: 'RAC' is not in list

### ISSUE THREAD

**Issue by mfalv** [aclouthier/auto-marker-label#8]
Hi,

I am attempting to use your tool with my own marker set as well as my own c3d files. I followed the instructions on the README file provided and I set the path to the folder containing the labelled c3d files and replaced the marker set xml file accordingly.

Nevertheless, when I run "trainAlgorithm.py", I run into the following issue:

Traceback (most recent call last):
  File "/auto-marker-label-main/trainAlgorithm.py", line 52, in <module>
    aml.trainAlgorithm(fld,datapath,markersetpath,fs,num_epochs,prevModel,windowSize,
  File "/auto-marker-label-main/automarkerlabel.py", line 219, in trainAlgorithm
    data_segs, windowIdx = import_labelled_c3ds(filelist,markers,
  File "/auto-marker-label-main/automarkerlabel.py", line 557, in import_labelled_c3ds
    pts = align(pts,markers.index(alignMkR),markers.index(alignMkL))
ValueError: 'RAC' is not in list

Any help you can provide would be greatly appreciated. 

Thank you.

**Comment by aclouthier** [comment]
I suspect the issue is that you don't have markers called RAC or LAC in your marker set. The training code uses two markers to align the data so that the person is facing the +x direction. I uses the right and left acromion markers (RAC, LAC) to do this. But you could also use pelvis markers, for example. You can specify which markers to use in trainAlgorithm.py, lines 47 and 48 where the variables alignMkR and alignMkL are defined.

**Comment by mfalv** [comment]
Brilliant - thanks!
